### ISSUE TITLE
Release version 4.3.0

### ISSUE THREAD

**Issue by jeffpaul** [10up/windows-azure-storage#103]
This issue is for tracking changes for the 4.3.0 release.  Target release date: **TBD**

### Pre-release steps
- [x] add CONTRIBUTING.md file including release instructions via #104
- [x] add CREDITS.md file with previous contributors, listing current maintainers
- [x] resolve issues in #102, then merge to `master`
- [x] ensure #99 is updated to include all changes in `master`, then merge
- [x] review #87 to see if it's viable for the 4.30 release, if so ensure it's updated to `develop` and then merge
- [x] review ~#84~ #102 to see if it's viable for the 4.30 release, if so ensure it's updated to `develop` and then merge
- [x] review #74 to see if it's viable for the 4.30 release, if so ensure it's updated to `develop` and then merge
- [x] ~review #70 to see if it's viable for the 4.30 release, if so ensure it's updated to `develop` and then merge~ punted to `Future Release`
- [x] merge #100

### [Release steps](https://github.com/10up/windows-azure-storage/blob/develop/CONTRIBUTING.md#release-instructions)

- [x] Starting from `develop`, cut a release branch named `release/4.3.0` for your changes.
- [x] Version bump: Bump the version number in `windows-azure-storage.php` and `readme.txt` if it does not already reflect the version being released.
- [x] Changelog: Add/update the changelog in both `readme.txt` and `CHANGELOG.md`.
- [x] Check to be sure any new files/paths that are unnecessary in the production version are included in `.distignore`.
- [x] Readme updates: Make any other readme changes as necessary. `CHANGELOG.md` and `README.md` are geared toward GitHub and `readme.txt` contains WordPress.org-specific content. The two are slightly different.
- [x] Merge: Make a non-fast-forward merge from `develop` to `master` (`git checkout master && git merge --no-ff develop`).

**STOP HERE UNTIL GITHUB ACTIONS CONFIRMED WORKING**

- [x] Release: Create a [new release](https://github.com/10up/windows-azure-storage/releases/new), naming the tag and the release with the new version number. Paste the changelog from `CHANGELOG.md` into the body of the release and include a link to the closed issues on the milestone (e.g. `https://github.com/10up/windows-azure-storage/milestone/2?closed=1`). Close the milestone.
- [x] SVN: Wait for the [GitHub Action](https://github.com/10up/windows-azure-storage/actions) to finish deploying to the WordPress.org repository. If all goes well, users with SVN commit access for that plugin will receive an emailed diff of changes.
- [x] Check WordPress.org: Ensure that the changes are live on [https://wordpress.org/plugins/windows-azure-storage/](https://wordpress.org/plugins/windows-azure-storage/). This may take a few minutes.
- [x] Edit the [4.3.0 milestone](https://github.com/10up/windows-azure-storage/milestone/2) with release date (in the `Due date (optional)` field) and link to GitHub release (in the `Description` field), then close `4.3.0` milestone.
- [x] If any open issues or PRs which were milestoned for `4.3.0` do not make it into the release, update their milestone to `4.4.0` or `Future Release`.

**Comment by jeffpaul** [comment]
Released, see: https://github.com/10up/windows-azure-storage/releases/tag/4.3.0
